---
- name: Configure servers
  hosts: all
  become: yes
  
  tasks:
  
  - name: Ping my servers
    ping:

  - name: add user
    user:
      name: user
      state: present
      shell: /bin/bash
      groups: sudo
      append: yes
  
  - name: create home directory and set permissions
    file:
      path: /home/user
      state: directory
      owner: user
      group: user
      mode: '0755'

  - name: create .ssh directory and set permissions
    file:
      path: /home/user/.ssh
      state: directory
      owner: user
      group: user
      mode: '0700'

  - name: create authorized file and set permissions
    file:
      path: /home/user/.ssh/authorized_keys
      state: touch
      owner: user
      group: user
      mode: '0600'

  - name: ssh copy id
    copy:
      src: ./dir_to_ignore/{{ hostname }}.pub
      dest: /home/user/.ssh/authorized_keys
      owner: user
      group: user
      mode: '0600'


  - name: accept sudoers
    copy:
      dest: /etc/sudoers.d/user
      content: "user ALL=(ALL) NOPASSWD:ALL\n"
      mode: '0440'

  - name: update apt cache
    apt:
      update_cache: yes 

  - name: install openssh-server
    apt:
      name: openssh-server
      state: present
      update_cache: yes



  #- name: deny password authentication
  #  shell: |
  #    sed -i 's/^#PasswordAuthentication yes/PasswordAuthentication no/' /etc/ssh/sshd_config
  #    systemctl restart sshd
